[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.7.6"
evm_version = 'shanghai'

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
