name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  forge-tests:
    name: Forge Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build
        run: forge build
        env:
          FOUNDRY_PROFILE: ci

      - name: Run tests
        run: forge test -vvv
        env:
          FOUNDRY_PROFILE: ci

